"""add user supervisor_id

Revision ID: 42b2e3e3eabc
Revises: c86666e649d3
Create Date: 2026-06-15 19:05:38.992553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b2e3e3eabc'
down_revision: Union[str, Sequence[str], None] = 'c86666e649d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supervisor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['supervisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'supervisor_id')
    # ### end Alembic commands ###
